//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2Projekat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        public int ProizvodjacIDMasina { get; set; }
        public int ProizvodIdProizvoda1 { get; set; }
    
        public virtual Proizvodjac Proizvodjac { get; set; }
        public virtual Proizvod Proizvod { get; set; }
    }
}
