//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2Projekat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProizvodnaOrganizacijaContainer : DbContext
    {
        public ProizvodnaOrganizacijaContainer()
            : base("name=ProizvodnaOrganizacijaContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Masina> Masinas { get; set; }
        public virtual DbSet<Magacin> Magacins { get; set; }
        public virtual DbSet<Paket> Pakets { get; set; }
        public virtual DbSet<Proizvodi> Proizvodis { get; set; }
        public virtual DbSet<Proizvod> Proizvods { get; set; }
    }
}
